work_name: Diffusion_LP_Deblur
model_name: DDM

data:
    type: IRdataset

    train_dataset: LOLv1
    val_dataset: LOLv1
    
    # patch_size: 256
    channels: 3
    num_workers: 2

    name: GoPro_crop
    train:
        dataroot_lq: /datadisk2/xuronghao/Datasets/GoPro/train/input
        dataroot_gt: /datadisk2/xuronghao/Datasets/GoPro/train/target
    val:
        dataroot_lq: /datadisk2/xuronghao/Datasets/GoPro/test/GoPro/input
        dataroot_gt: /datadisk2/xuronghao/Datasets/GoPro/test/GoPro/target

    # LLdataset
    # data_dir: /datasata/lxn/LowLight/LOL/LOLdataset/our485 # "our485"
    ckpt_dir: /datadisk2/xuronghao/Projects/Basic/ckpt
    conditional: True

VAE:
    type: LP
    LP:
        num_high: 5 #/16
        # Low-light，hdr：6
        in_chans: 3
        drop_rate: 0.0
        embed_dim: 16
# Unet
model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

DiT:
    patch_size: 1
    in_chans: 16 #16 OOM
    t_ch: 16
    hidden_size: 256
    depth: 6
    num_heads: 4
    mlp_ratio: 4.0
    drop_rate: 0.0

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    # [per gpu]
    batch_size: 4 # 4-512-OOM
    val_batch_size: 1
    n_epochs: 500
    log_freq: 10
    validation_freq: 1000

optim:
    weight_decay: 0.000
    optimizer: Adam
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8

accelerator: 
    mixed_precision: fp16 # "no", "fp16", "bf16"
    gradient_accumulation_steps: 2 # 表示每 4 个 batch 才更新一次。

loss:
    photo_loss_w: 0 # gt_img vs pred_img
    ssim_loss_w: 0
    noise_loss_w: 1.0 # diffsuion
    pred_loss_w: 1.0 # 隐空间

    frequency_loss_w: 1.0 # 隐空间

DEBUG: True #True：debug模式，不保存任何日志和模型文件；False：保存日志和模型文件

wandb:
    is_use_wandb: True
    APIkeys: a887abe896653dfe4d9247ad2a5f5717734c0e11
    # team
    entity: DiffLLIR
    # dir_root: /datadisk2/xuronghao/Projects/Diffusion-Low-Light-main/wandb
    # User
    ### entity
    ###### project
    ######## name
###
###    data_dict["pred"] = denoise_high ## 隐空间扩散量
###    data_dict["noise_output"] = noise_output ## 隐空间噪声
###    data_dict["e"] = e